"""add is_active to employees

Revision ID: e0171c4aeecd
Revises: 550b0656bfbf
Create Date: 2026-06-21 19:59:56.817868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0171c4aeecd'
down_revision: Union[str, Sequence[str], None] = '550b0656bfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
